### ISSUE TITLE
Cannot compile files with imported variables

### ISSUE THREAD

**Issue by monolithed** [jaywcjlove/compile-less#28]
**theme/index.less**

```less
@button: #0091FF;

```

**index.less**

```less
@import '../../theme/index.less';

.foo {
    background-color: @button;
}
```

```
> compile-less -d ./build -o css

error: [LessError: variable @button is undefined] {
  type: 'Name',
  filename: 'input',
  index: 59,
  line: 3,
  column: 26,
  callLine: NaN,
  callExtract: undefined,
  extract: [
    '        background-color: @button;',
  ]
}
```
